#!/bin/bash

#NOTE: Thist script allows you to automatically download, execute and remove the script locally

echo "This script requires git"
echo "If you do not have git, please download it"

git clone https://github.com/bobafett2010/Deployment.git
chmod +x Deployment/*.sh



 










rm -r Deployment 
